---
# tasks file for install-osp13-director
- include: base-system.yaml 
- include: satellite-register.yaml
- include: system-updates.yaml
- include: base-services.yaml
- include: undercloud-install.yaml
#- include: git-overcloud-templates.yaml
