---
- name: 'Get current Satellite registration status.'
  command: subscription-manager status
  register: reg_status
  ignore_errors: yes
  changed_when: false
  tags:
    - sat_install

- name: 'Clean any lingering registration details from previous attempts.'
  shell: > 
    subscription-manager clean

- name: 'Install katello consumer CA on host [If not registered].'
  yum:
    name: '{{ katello_rpm_url }}'
    state: present
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  when: "'Unknown' in reg_status.stdout"
  tags:
    - sat_install

- name: 'Enable Satellite Registration [If not registered]'
  redhat_subscription:
    server_hostname: '{{ satellite_host }}'
    org_id: '{{ rhn_org }}'
    activationkey: '{{ rhn_activation_key }}'
    state: present
    force_register: yes
  when: "'Unknown' in reg_status.stdout"
  register: sat_registration
  until: sat_registration is succeeded
  retries: 10
  delay: 5
  tags:
    - sat_install

- name: 'Disable all repositories not required.'
  rhsm_repository:
    name: '*'
    state: disabled
  when: sat_registration.changed
  retries: 10 
  delay: 5
  tags:
    - sat_install

- name: 'Enable the configured repositories from the vars file'
  rhsm_repository:
    name: '{{ rhn_rpm_repos }}'
    state: enabled
  when: sat_registration.changed
  register: repo_enabled
  retries: 10 
  delay: 5
  tags:
    - sat_install
